# Generated by Django 6.0.1 on 2026-02-18 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_rules', models.TextField(help_text='The original raw firewall rules input')),
                ('rule_type', models.CharField(choices=[('iptables', 'iptables'), ('nftables', 'nftables')], default='iptables', max_length=20)),
                ('total_rules', models.IntegerField(default=0)),
                ('redundant_count', models.IntegerField(default=0)),
                ('shadowed_count', models.IntegerField(default=0)),
                ('conflict_count', models.IntegerField(default=0)),
                ('optimized_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
